package view;

import dto.OgrenciSinifOgretmenTableDto;
import entitites.Ogrenci;
import entitites.Ogretmen;
import entitites.Sinif;
import project.*;
import java.sql.*;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import services.OgrenciService;
import services.OgretmenService;
import services.SinifService;

/**
 *
 * @author bedirhan
 */
public class OgrenciList extends javax.swing.JFrame {

    OgrenciService ogrenciService;
    SinifService sinifService;
    OgretmenService ogretmenService;

    DefaultTableModel model;

    List<OgrenciSinifOgretmenTableDto> ogrenciler = new ArrayList<>();

    public OgrenciList() {
        initComponents();
        ogrenciService = new OgrenciService();
        sinifService = new SinifService();
        ogretmenService = new OgretmenService();
        sinifListele();
    }

    public void sinifListele() {
        sinifComboBox1.removeAllItems();
        List<Sinif> siniflar = sinifService.findAll();
        siniflar.forEach(i -> {
            sinifComboBox1.addItem(i.getNo());
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        adTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        sinifComboBox1 = new javax.swing.JComboBox<>();
        soyadTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        dogumTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ekleButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        teimzleButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kres Yonetim");
        setBackground(new java.awt.Color(255, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(50, 123));
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Ogrenci Ekle");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Ad", "Soyad", "Sınıf", "Öğretmen"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Ad");

        adTextField1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        adTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adTextField1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Soyad");

        sinifComboBox1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sinifComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sinifComboBox1ActionPerformed(evt);
            }
        });

        soyadTextField2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setText("Sınıflar");

        dogumTextField3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        dogumTextField3.setToolTipText("16-06-1996");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Dogum Yili");

        ekleButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ekleButton3.setText("Ogrenci Ekle");
        ekleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ekleButton3ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Sınıf");

        teimzleButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        teimzleButton4.setText("Temizle");
        teimzleButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teimzleButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(sinifComboBox1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(ekleButton3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(teimzleButton4))
                                .addComponent(dogumTextField3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(adTextField1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                                .addComponent(soyadTextField2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(130, 295, Short.MAX_VALUE))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(135, 135, 135)
                    .addComponent(jLabel6)
                    .addContainerGap(1045, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(adTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(24, 24, 24)
                        .addComponent(soyadTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(dogumTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sinifComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ekleButton3)
                            .addComponent(teimzleButton4))))
                .addContainerGap(60, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(51, 51, 51)
                    .addComponent(jLabel6)
                    .addContainerGap(517, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sinifComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sinifComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sinifComboBox1ActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown

        List<OgrenciSinifOgretmenTableDto> ogrenciler = ogrenciService.findAllTableDto();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        ogrenciler.forEach(i -> {
            model.addRow(new Object[]{i.getOgrenciId(), i.getOgrenciAd(), i.getOgrenciSoyad(), i.getSinifNo(), i.getOgretmenAdSoyad()});
        });
    }//GEN-LAST:event_formComponentShown

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        // TODO add your handling code here:
        cleanFields();

        model = (DefaultTableModel) jTable1.getModel();
        int index = jTable1.getSelectedRow();
        String sinifId = model.getValueAt(index, 0).toString();
        String sinifNo = model.getValueAt(index, 1).toString();
        kapasite = model.getValueAt(index, 2).toString();
        String ogretmen;
        if (model.getValueAt(index, 3) != null) {
            guncellemeMi = 1;
            ogretmen = model.getValueAt(index, 3).toString();
            dogumTextField3.setText(ogretmen);
        }

        adTextField1.setText(sinifNo);
        soyadTextField2.setText(kapasite);

        ekleButton3.setText("Sınıfı Guncelle");
    }//GEN-LAST:event_jTable1MouseClicked

    private void ekleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ekleButton3ActionPerformed
        // TODO add your handling code here:
        Ogrenci ogrenci = new Ogrenci();
        ogrenci.setAd(adTextField1.getText());
        ogrenci.setSoyad(soyadTextField2.getText());
        ogrenci.setDogumYili(Integer.parseInt(dogumTextField3.getText()));

        Sinif sinif = sinifService.findByNo(sinifComboBox1.getSelectedItem().toString());

        ogrenci.setSinif(sinif);
        ogrenciService.save(ogrenci);

        setVisible(false);
        new OgrenciList().setVisible(true);
    }//GEN-LAST:event_ekleButton3ActionPerformed

    private void teimzleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teimzleButton4ActionPerformed
        cleanFields();
    }//GEN-LAST:event_teimzleButton4ActionPerformed

    private void adTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adTextField1ActionPerformed

    public void cleanFields() {
        // TODO add your handling code here:
        adTextField1.setText("");
        soyadTextField2.setText("");
        dogumTextField3.setText("");
    }

    /*
     */
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OgrenciList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OgrenciList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OgrenciList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OgrenciList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OgrenciList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adTextField1;
    private javax.swing.JTextField dogumTextField3;
    private javax.swing.JButton ekleButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> sinifComboBox1;
    private javax.swing.JTextField soyadTextField2;
    private javax.swing.JButton teimzleButton4;
    // End of variables declaration//GEN-END:variables
}
